// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NestedForm from "./nested_form_controller.js"
application.register("nested-form", NestedForm)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import CheckboxListController from "./checkbox_list_controller.js"
application.register("checkbox-list", CheckboxListController)
