// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller.js"
application.register("chart", ChartController)

import CheckboxListController from "./checkbox_list_controller.js"
application.register("checkbox-list", CheckboxListController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)

import XmlConsoleController from "./xml_console_controller.js"
application.register("xml-console", XmlConsoleController)