FROM ruby:3.1.1

RUN apt-get update && apt-get install -y --no-install-recommends \
    npm \
    build-essential \
    git \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install -g yarn@latest

COPY package.json ./
RUN yarn install --check-files

WORKDIR /opt/webapps/app

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 3000

# CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
# CMD ["bin/dev"]
