name: Github Testing
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        ruby: [ '3.2.2' ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:

      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: config bundler
        run:  |
          bundle config set without 'development staging production'
          bundle config set deployment '[secure]'
          bundle env
          head -n1 $(which bundle)

      - name: Install wkhtmltopdf (push)
        run: |
          sudo apt-get install -y xfonts-base xfonts-75dpi
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6.1-2.jammy_amd64.deb
        if: github.event_name == 'push'

      - name: Run Tests
        env:
          REPP_HOST: http://registry:3000
          REPP_ENDPOINT: /repp/v1
          RAILS_ENV: test
          COVERAGE: true
          DISABLE_SPRING: 1
        run: |
          cp config/application.yml.sample config/application.yml
          yarn install --check-files && yarn sass-migrator division **/*.scss
          bundle exec rails assets:precompile
          bundle exec rspec

  code_quality:
    runs-on: ubuntu-22.04
    needs: test
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup qlty.sh
        run: |
          curl -sSL https://qlty.sh/install.sh | bash
          
      - name: Run qlty.sh analysis
        env:
          QLTY_TOKEN: ${{ secrets.QLTY_TOKEN }}
        run: |
          qlty analyze \
            --repo="${{ github.repository }}" \
            --pr="${{ github.event.number }}" \
            --commit="${{ github.sha }}" \
            --base="${{ github.event.pull_request.base.sha }}" \
            --coverage-path="coverage/.resultset.json"